# This file was generated by GitHub Copilot agent mode.

from django.core.management.base import BaseCommand
from django.contrib.auth.hashers import make_password
from octofit_tracker.test_data import test_users, test_teams, test_activities, test_leaderboard, test_workouts
from octofit_tracker.models import User, Team, Activity, Leaderboard, Workout

class Command(BaseCommand):
    help = 'Populate the database with test data'

    def handle(self, *args, **kwargs):
        # Populate users
        for user_data in test_users:
            user, created = User.objects.get_or_create(email=user_data['email'], defaults={
                'name': user_data['name'],
                'password': make_password(user_data['password'])
            })
            if created:
                self.stdout.write(f"Created user: {user.email}")
            else:
                self.stdout.write(f"User already exists: {user.email}")

        # Populate teams
        for team_data in test_teams:
            team = Team.objects.create(name=team_data['name'])
            for email in team_data['members']:
                user = User.objects.get(email=email)
                team.members.add(user)

        # Populate activities
        for activity_data in test_activities:
            user = User.objects.first()  # Assign the first user as a placeholder
            Activity.objects.create(user=user, **activity_data)

        # Populate leaderboard
        for leaderboard_data in test_leaderboard:
            user = User.objects.get(email=leaderboard_data['user'])  # Fetch the User instance by email
            team = Team.objects.first()  # Assign the first team as a placeholder
            Leaderboard.objects.create(user=user, team=team, score=leaderboard_data['score'])

        # Populate workouts
        for workout_data in test_workouts:
            Workout.objects.create(**workout_data)

        self.stdout.write(self.style.SUCCESS('Database populated with test data.'))
