# Generated by Django 4.1 on 2025-04-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", to="octofit_tracker.user"
            ),
        ),
    ]
