# Generated by Django 4.1 on 2025-04-09 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_team_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="calories_burned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
