# Generated by Django 4.1 on 2025-04-09 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0003_activity_calories_burned_activity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="score",
            field=models.IntegerField(default=0),  # Corrected default value to an integer
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="user",
            field=models.ForeignKey(
                default=1,  # Use a valid User ID as the default
                on_delete=django.db.models.deletion.CASCADE,
                to="octofit_tracker.user",
            ),
            preserve_default=False,
        ),
    ]
