# Generated by Django 4.1 on 2025-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0004_leaderboard_score_leaderboard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
