# Generated by Django 4.1 on 2025-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0005_alter_leaderboard_score"),
    ]

    operations = []
