# Generated by Django 4.1 on 2025-04-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0006_auto_20250409_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="activity",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
